const varBanks = [
  { value: '009', text: 'BANK BNI' },
  { value: '427', text: 'BANK BNI SYARIAH' },
  { value: '002', text: 'BANK BRI' },
  { value: '003', text: 'BANK EKSPOR INDONESIA' },
  { value: '008', text: 'BANK MANDIRI' },
  { value: '011', text: 'BANK DANAMON' },
  { value: '013', text: 'PERMATA BANK' },
  { value: '014', text: 'BANK BCA' },
  { value: '016', text: 'BANK BII' },
  { value: '019', text: 'BANK PANIN' },
  { value: '020', text: 'BANK ARTA NIAGA KENCANA' },
  { value: '022', text: 'BANK NIAGA' },
  { value: '023', text: 'BANK BUANA IND' },
  { value: '026', text: 'BANK LIPPO' },
  { value: '028', text: 'BANK NISP' },
  { value: '030', text: 'AMERICAN EXPRESS BANK LTD' },
  { value: '032', text: 'JP. MORGAN CHASE BANK N.A.' },
  { value: '033', text: 'BANK OF AMERICA N.A' },
  { value: '034', text: 'ING INDONESIA BANK' },
  { value: '036', text: 'BANK MULTICOR TBK.' },
  { value: '037', text: 'BANK ARTHA GRAHA' },
  { value: '039', text: 'BANK CREDIT AGRICOLE INDOSUEZ' },
  { value: '040', text: 'THE BANGKOK BANK COMP. LTD' },
  { value: '041', text: 'THE HONGKONG & SHANGHAI B.C.' },
  { value: '042', text: 'THE BANK OF TOKYO MITSUBISHI UFJ LTD' },
  { value: '045', text: 'BANK SUMITOMO MITSUI INDONESIA' },
  { value: '046', text: 'BANK DBS INDONESIA' },
  { value: '047', text: 'BANK RESONA PERDANIA' },
  { value: '048', text: 'BANK MIZUHO INDONESIA' },
  { value: '050', text: 'STANDARD CHARTERED BANK' },
  { value: '052', text: 'BANK ABN AMRO' },
  { value: '053', text: 'BANK KEPPEL TATLEE BUANA' },
  { value: '054', text: 'BANK CAPITAL INDONESIA TBK.' },
  { value: '057', text: 'BANK BNP PARIBAS INDONESIA' },
  { value: '058', text: 'BANK UOB INDONESIA' },
  { value: '059', text: 'KOREA EXCHANGE BANK DANAMON' },
  { value: '060', text: 'RABOBANK INTERNASIONAL INDONESIA' },
  { value: '061', text: 'ANZ PANIN BANK' },
  { value: '067', text: 'DEUTSCHE BANK AG.' },
  { value: '068', text: 'BANK WOORI INDONESIA' },
  { value: '069', text: 'BANK OF CHINA LIMITED' },
  { value: '076', text: 'BANK BUMI ARTA' },
  { value: '087', text: 'BANK EKONOMI' },
  { value: '088', text: 'BANK ANTARDAERAH' },
  { value: '089', text: 'BANK HAGA' },
  { value: '093', text: 'BANK IFI' },
  { value: '095', text: 'BANK CENTURY TBK.' },
  { value: '097', text: 'BANK MAYAPADA' },
  { value: '110', text: 'BANK JABAR' },
  { value: '111', text: 'BANK DKI' },
  { value: '112', text: 'BPD DIY' },
  { value: '113', text: 'BANK JATENG' },
  { value: '114', text: 'BANK JATIM' },
  { value: '115', text: 'BPD JAMBI' },
  { value: '116', text: 'BPD ACEH' },
  { value: '117', text: 'BANK SUMUT' },
  { value: '118', text: 'BANK NAGARI' },
  { value: '119', text: 'BANK RIAU' },
  { value: '120', text: 'BANK SUMSEL' },
  { value: '121', text: 'BANK LAMPUNG' },
  { value: '122', text: 'BPD KALSEL' },
  { value: '123', text: 'BPD KALIMANTAN BARAT' },
  { value: '124', text: 'BPD KALTIM' },
  { value: '125', text: 'BPD KALTENG' },
  { value: '126', text: 'BPD SULSEL' },
  { value: '127', text: 'BANK SULUT' },
  { value: '128', text: 'BPD NTB' },
  { value: '129', text: 'BPD BALI' },
  { value: '130', text: 'BANK NTT' },
  { value: '131', text: 'BANK MALUKU' },
  { value: '132', text: 'BPD PAPUA' },
  { value: '133', text: 'BANK BENGKULU' },
  { value: '134', text: 'BPD SULAWESI TENGAH' },
  { value: '135', text: 'BANK SULTRA' },
  { value: '145', text: 'BANK NUSANTARA PARAHYANGAN' },
  { value: '146', text: 'BANK SWADESI' },
  { value: '147', text: 'BANK MUAMALAT' },
  { value: '151', text: 'BANK MESTIKA' },
  { value: '152', text: 'BANK METRO EXPRESS' },
  { value: '153', text: 'BANK SHINTA INDONESIA' },
  { value: '157', text: 'BANK MASPION' },
  { value: '159', text: 'BANK HAGAKITA' },
  { value: '161', text: 'BANK GANESHA' },
  { value: '162', text: 'BANK WINDU KENTJANA' },
  { value: '164', text: 'HALIM INDONESIA BANK' },
  { value: '166', text: 'BANK HARMONI INTERNATIONAL' },
  { value: '167', text: 'BANK KESAWAN' },
  { value: '200', text: 'BANK TABUNGAN NEGARA (PERSERO)' },
  { value: '212', text: 'BANK HIMPUNAN SAUDARA 1906 TBK .' },
  { value: '213', text: 'BANK TABUNGAN PENSIUNAN NASIONAL' },
  { value: '405', text: 'BANK SWAGUNA' },
  { value: '422', text: 'BANK JASA ARTA' },
  { value: '426', text: 'BANK MEGA' },
  { value: '441', text: 'BANK BUKOPIN' },
  { value: '451', text: 'BANK SYARIAH MANDIRI' },
  { value: '459', text: 'BANK BISNIS INTERNASIONAL' },
  { value: '466', text: 'BANK SRI PARTHA' },
  { value: '472', text: 'BANK JASA JAKARTA' },
  { value: '484', text: 'BANK BINTANG MANUNGGAL' },
  { value: '485', text: 'BANK BUMIPUTERA' },
  { value: '490', text: 'BANK YUDHA BHAKTI' },
  { value: '491', text: 'BANK MITRANIAGA' },
  { value: '494', text: 'BANK AGRO NIAGA' },
  { value: '498', text: 'BANK INDOMONEX' },
  { value: '501', text: 'BANK ROYAL INDONESIA' },
  { value: '503', text: 'BANK ALFINDO' },
  { value: '506', text: 'BANK SYARIAH MEGA' },
  { value: '513', text: 'BANK INA PERDANA' },
  { value: '517', text: 'BANK HARFA' },
  { value: '520', text: 'PRIMA MASTER BANK' },
  { value: '521', text: 'BANK PERSYARIKATAN INDONESIA' },
  { value: '525', text: 'BANK AKITA' },
  { value: '526', text: 'LIMAN INTERNATIONAL BANK' },
  { value: '531', text: 'ANGLOMAS INTERNASIONAL BANK' },
  { value: '523', text: 'BANK DIPO INTERNATIONAL' },
  { value: '535', text: 'BANK KESEJAHTERAAN EKONOMI' },
  { value: '536', text: 'BANK UIB' },
  { value: '542', text: 'BANK ARTOS IND' },
  { value: '547', text: 'BANK PURBA DANARTA' },
  { value: '548', text: 'BANK MULTI ARTA SENTOSA' },
  { value: '553', text: 'BANK MAYORA' },
  { value: '555', text: 'BANK INDEX SELINDO' },
  { value: '566', text: 'BANK VICTORIA INTERNATIONAL' },
  { value: '558', text: 'BANK EKSEKUTIF' },
  { value: '559', text: 'CENTRATAMA NASIONAL BANK' },
  { value: '562', text: 'BANK FAMA INTERNASIONAL' },
  { value: '564', text: 'BANK SINAR HARAPAN BALI' },
  { value: '567', text: 'BANK HARDA' },
  { value: '945', text: 'BANK FINCONESIA' },
  { value: '946', text: 'BANK MERINCORP' },
  { value: '947', text: 'BANK MAYBANK INDOCORP' },
  { value: '948', text: 'BANK OCBC – INDONESIA' },
  { value: '949', text: 'BANK CHINA TRUST INDONESIA' },
  { value: '950', text: 'BANK COMMONWEALTH' },
  { value: '425', text: 'BANK BJB SYARIAH' },
  { value: '688', text: 'BPR KS (KARYAJATNIKA SEDAYA)' },
  { value: '789', text: 'INDOSAT DOMPETKU' },
  { value: '911', text: 'TELKOMSEL TCASH' },
  { value: '911', text: 'LINKAJA' }
];

export default varBanks;
